#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard        !!*//

/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

#pragma autonomousDuration(15)
#pragma userControlDuration(120)
// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton() {
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/


task autonomous() {
	
}


void lineFollow(int fast, int slow) {

	if (vexRT[Btn5D]) {return;}

	if (SensorValue(rightIR) > 200 ) {
		setMotor(rightMotor, -fast);
	}

	if (SensorValue(rightIR) < 200) {
		setMotor(rightMotor, -slow);
	}

	if (SensorValue (leftIR) > 200) {
		setMotor(leftMotor, -fast);
	}

	if (SensorValue (leftIR) < 200) {
	 	setMotor(leftMotor, -slow);
	}
}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol() {
	enableCompetitionMode();

	while (true) {
		//Custom arcade control
		motor[leftMotor] = (vexRT[Ch3] + vexRT[Ch4]);
		motor[rightMotor] = (vexRT[Ch3] - vexRT[Ch4]);

		if (vexRT[Btn5U]) {
			for (int i = 0; i <1000000; i++) {
				if (i < 5000) {
					lineFollow(69, 20);
				} else if (5000 < y < 70000) {
					lineFollow(73, 29);
				} else if (70000 < y <120000) {
					lineFollow(69, 20);
				} else {
					lineFollow(73, 29);
				}
			}
		}
	}
}