#pragma config(Sensor, in2,    IRL,            sensorLineFollower)
#pragma config(Sensor, in3,    IRR,            sensorLineFollower)
#pragma config(Motor,  port2,           RDrive,        tmotorServoContinuousRotation, openLoop, driveRight)
#pragma config(Motor,  port3,           core1,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           core2,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           Elevator,      tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           LDrive,        tmotorServoContinuousRotation, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "VG_robotDimensions.h"
float distanceL = 0;
float distanceR = 0;
bool clawOpen = false;

#include "VG_Distance.h"
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
//If you see errors here ignore them, they work in the robotc compiler
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	/* Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
		 used by the competition include file, for example, you might want
		 to display your team name on the LCD in this function. */
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	autoDrive2(1, 60, 90);

	float targetDistance = 90;
	while (distanceL < targetDistance && distanceR < targetDistance) {
		distanceL = autoDrive(1, IRL, LDrive, -80, distanceL);
		distanceR = autoDrive(1, IRR, RDrive, 80, distanceR);
	}

	targetDistance = 48;
	while (distanceL < targetDistance && distanceR < targetDistance) {
		distanceL = autoDrive(0, IRL, LDrive, 30, distanceL);
		distanceR = autoDrive(0, IRR, RDrive, 30, distanceR);
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void elevatorControl(float speed, bool up, bool down){
	if(up == true) {
		setMotor(Elevator, speed);
	}	else if(down == true){
		setMotor(Elevator, -speed);
	}	else {
		setMotor(Elevator, 0);
	}
}

void clawControl(bool button, float open, float close){
	if (button){
		if (clawOpen == false){
			setMultipleMotors(open, core1, core2);
		} else {
			setMultipleMotors(close, core1, core2);
		}
	}
}

void customArcade(float leftmotor, float rightmotor, float forward, float turn) {
	setMotor(leftmotor, forward - turn);
	setMotor(rightmotor, forward + turn);
}

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		// This is the main execution loop for the user control program.
		// Each time through the loop your program should update motor + servo
		// values based on feedback from the joysticks.

		customArcade(LDrive, RDrive, vexRT[Ch3], vexRT[Ch4]);

		//This code uses the elevator
		elevatorControl(127, vexRT[Btn6U], vexRT[Btn6D]);

		//toggles open the claw grip
		clawControl(vexRT[Btn7D], 45, -45);

		distanceL = motionCalculation(distanceL, IRL, 0);
		distanceR = motionCalculation(distanceR, IRR, 0);
		if (vexRT[Btn5D]) {
			startTask(autonomous);
		}
	}
}