#pragma config(Motor,  port2,           LDrive,        tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port3,           RDrive,        tmotorServoContinuousRotation, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task autonomous (){
	setMotor(LDrive, 127);
	setMotor(RDrive, 127);
	wait(1000);

}

task main(){
	while(true){
		setMotor(LDrive, 50);
		setMotor(RDrive, 50);
		motor[LDrive] = (vexRT[Ch3] + vexRT[Ch4]);
		motor[RDrive] = (vexRT[Ch3] - vexRT[Ch4]);

	}

	startTask(autonomous);


}
