#pragma config(Sensor, in2,    IR,             sensorLineFollower)
#pragma config(Motor,  port2,           RDrive,        tmotorServoContinuousRotation, openLoop, driveRight)
#pragma config(Motor,  port3,           LeftClawServo, tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           RightClawServo, tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           ElevatorMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           LDrive,        tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int holeCount = 34;
float wheelDiameter = 12;
float distance = 0;

#include "VG_Distance.h"
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
//If you see errors here ignore them, they work in the robotc compiler
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	while (true)
	{
		// This is the main execution loop for the user control program.
		// Each time through the loop your program should update motor + servo
		// values based on feedback from the joysticks.

		motor[LDrive] = (vexRT[Ch3] + vexRT[Ch4]);
		motor[RDrive] = (vexRT[Ch3] - vexRT[Ch4]);
		distance = distCalc(distance);

		if(vexRT[Btn6D]){
			setMotor(ElevatorMotor,127);
		}
		else if(vexRT[Btn6U]){
			setMotor(ElevatorMotor,-127);
		}
		else{
			setMotor(ElevatorMotor,0);
		}
		if(vexRT[Btn5D]){
			setMotor(LeftClawServo,127);
			setMotor(RightClawServo,-127);
		}
		else if(vexRT[Btn5U]){
			setMotor(LeftClawServo,-127);
			setMotor(RightClawServo,127);
		}
		else{
			setMotor(LeftClawServo,0);
			setMotor(RightClawServo,0);
		}
	}
}
