#pragma config(Motor,  port2,           Lefty,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           Righty,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           LimitSwitch,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           ElvtorMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,            ,             tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while (true)
	{
		motor[Lefty]= (vexRT[Ch3] + vexRT[Ch4]);
		motor[Righty]= (vexRT[Ch3] - vexRT[Ch4]);
		if (vexRT[Btn6U] == 1) {
			setMotor(ElvtorMotor, -127);
			}	else if  (vexRT[Btn6D] == 1 && SensorValue[LimitSwitch] == 1){
			setMotor(ElvtorMotor,127);
			}	else if (vexRT[Btn6D] == 1 && SensorValue[LimitSwitch] == 0) {
			setMotor(ElvtorMotor,127);
			}	else {
			setMotor(ElvtorMotor, 0);
		};
	}
}
